### ISSUE TITLE
Support for controllable global phase changes

### ISSUE THREAD

**Issue by Strilanc** [ProjectQ-Framework/ProjectQ#11]
Currently, the example code in grover.py has this:

		with Control(eng, x[0:-1]):
			Z | x[-1]

But it would be clearer to do something like this:

		with Control(eng, x):
			PhaseFlip | []

Where `PhaseFlip` is a gate defined like this:

```python
class GlobalPhase(SelfInverseGate):
	def __init__(self, phase_factor):
		super().__init__()
		self.phase_factor = phase_factor

	def __str__(self):
		return str(self.phase_factor)

	@property
	def matrix(self):
		return np.matrix([[self.phase_factor]])

PhaseFlip = GlobalPhase(-1)
```

This gate is a bit unusual, since it has no targets. That's why I opened this issue; I assume it'll break all kinds of code if I use it. But many algorithms get minor simplifications from the "just change the phase of all states meeting the current controls" operation.

For example, the `alternating_bits_oracle` has an output parameter. But it really doesn't need one:

```python
def alternating_bits_oracle(eng, qubits):
	with Compute(eng):
		All(X) | qubits[1::2]
	with Control(eng, qubits):
		PhaseFlip | []
	Uncompute(eng)
```

To implement a global phase gate, you just arbitrarily pick one of the controls and apply a Z rotation to it. If there's no controls to pick from, just do nothing.

**Comment by thomashaener** [comment]
Maybe a new gate, e.g., ``CPhaseFlip | qureg`` with the default decomposition rule above would do the job?

**Comment by thomashaener** [comment]
@Strilanc would such a gate address this issue?

**Comment by Strilanc** [comment]
A conditioned global phase flip doesn't really have a target, it only has controls. You would apply it to the empty tuple, not to qureg.

**Comment by thomashaener** [comment]
Yes, this is why I propose `CPhaseFlip`:
```
CPhaseFlip | control_qubits
```

**Comment by Strilanc** [comment]
The context I had in mind was in a method being affected by a `with Control(control_qubits)`, so the code invoking the phase doesn't know the control qubits directly.

**Comment by thomashaener** [comment]
My issue with having a gate acting on no qubits is that one would expect it to be the identity -- but it's only the identity if there are no control qubits, which is really weird.

**Comment by thomashaener** [comment]
Oh I see, but that's fine since that code could just apply a global phase gate to any qubit it knows (and I guess it knows at least one :) )
