### ISSUE TITLE
Native compilation causes issues on distributed systems

### ISSUE THREAD

**Issue by obriente** [ProjectQ-Framework/ProjectQ#120]
Compilation of the C++ backend currently has a hard-coded '-march=native' option as part of the setup instructions. This causes problems when a single python environment is used across multiple machines with different hardware; importing ProjectQ will cause immediate kernel death with no error message.

Would it be possible to add a setup flag for this instead of hard-coding?

**Comment by thomashaener** [comment]
I currently don't know of a nice way to achieve this. As with features I suspect that this will cause problems when using pip (instead of running setup.py).
As a quick fix, I'd clone the repo, replace the flag in setup.py and install that version. Does this work for now?

**Comment by obriente** [comment]
This workaround works fine, although installing manually rather than via pip is always slightly more complicated. In lieu of a better option for the install itself, it might be an idea to mention it in the installation documentation; it was very difficult for us to diagnose this when we encountered the error.

**Comment by damiansteiger** [comment]
Thanks for the suggestion and mentioning this issue to us. We have now included a notice in the latest documentation.
