### ISSUE TITLE
Method to provide C++ simulator with arbitrary initial state

### ISSUE THREAD

**Issue by babbush** [ProjectQ-Framework/ProjectQ#124]
I think this may have been mentioned before but it is now becoming a bottleneck for two different ongoing projects that I am involved with. Ideally, one should be able to provide a vector as input. I realize this isn't something that can be done with an actual quantum computer as the backend but it is something that people expect of a simulator.

**Comment by damiansteiger** [comment]
This was already added recently:

http://projectq.readthedocs.io/en/latest/projectq.backends.html#projectq.backends.Simulator.set_wavefunction

For code examples, please see the docs, the tests, and soon (this week) we will upload a new tutorial for the simulator...
