### ISSUE TITLE
Project Q

### ISSUE THREAD

**Issue by faheem11126** [ProjectQ-Framework/ProjectQ#135]
Can anyone Tell me 
the uses of this  framwork .

**Comment by faheem11126** [comment]
what kind of Project I can make with the help of this framework

**Comment by damiansteiger** [comment]
It allows to program quantum algorithms and run time either on hardware or in a simulation.

I would suggest to have a look at the paper about this framework:
https://arxiv.org/pdf/1612.08091.pdf

And then look into the tutorial and installation guide:
http://projectq.readthedocs.io/en/latest/tutorials.html

Finally, the examples give quite a good overview of what can be done with ProjectQ:
https://github.com/ProjectQ-Framework/ProjectQ/tree/develop/examples
