### ISSUE TITLE
Control's `eng` parameter is redundant (get it from the qubits instead)

### ISSUE THREAD

**Issue by Strilanc** [ProjectQ-Framework/ProjectQ#14]
```with Control(eng, ctrl_qubit):```

is basically always equivalent to:

```with Control(ctrl_qubit.engine, ctrl_qubit):```

I think. Otherwise the code is wrong. So might as well pull out that value inside the control constructor:

```with Control(ctrl_qubit):```

Of course you need to check for lists, etc.

**Comment by thomashaener** [comment]
The idea behind this is to have ``eng`` as a first parameter for _all_ ``with`` statements (to make it easier for users).

**Comment by Strilanc** [comment]
Alright
