### ISSUE TITLE
Compatibility issues with new pybind11 version 2.2.0

### ISSUE THREAD

**Issue by damiansteiger** [ProjectQ-Framework/ProjectQ#144]
Our installation breaks since yesterday as by default we are using the latest pybind11 which is now v2.2.0.

A workaround for the moment is to install pybind v2.1.1 (`pip install pybind==2.1.1`) prior to installing ProjectQ until we have fixed the compatibility issues. 

The build failure can be seen in #142 (or any other pull request after rebuilding it)

**Comment by damiansteiger** [comment]
A work around for this issue has been submitted. ProjectQ v0.3.3 should work fine again.

Soon we will make ProjectQ compatible with the latest version of pybind11.

**Comment by thomashaener** [comment]
This is an issue with the newest version of pybind11. There is a PR on their github which indicates that this will be fixed in v2.2.1.

**Comment by thomashaener** [comment]
Closing this issue since this bug has been fixed in v2.2.1 of pybind11. ProjectQ requirements will exclude the buggy version 2.2.0.
