### ISSUE TITLE
Controlled rotation gate w/IBM Backend

### ISSUE THREAD

**Issue by erikweis** [ProjectQ-Framework/ProjectQ#182]
I am having an issue implementing a controlled rotation gate using the IBM backend. I think the gate decomposition in the IBMCNOTMapper compiler is not working, as I am receiving an assertion error, that the control count for the gate should be zero.

Thanks for your help! (I am an undergrad with limited coding experience, so my understanding of the error message is not great.)

My code is here.

[Rz_test.txt](https://github.com/ProjectQ-Framework/ProjectQ/files/1413027/Rz_test.txt)

**Comment by thomashaener** [comment]
Just remove your explicit `engine_list=[IBMCNOTMapper()]`. This overwrites the default engines which would try to compile your controlled rotation to the IBM gate set.
You might want to change your IBM QE password now ;-)

**Comment by damiansteiger** [comment]
Here is a cleanup version of your program (I slightly change the algorithm as I was not sure what you intended to do).

Please have a look at the example folder.

```
import math

import projectq.setups.ibm
from projectq import MainEngine
from projectq.backends import IBMBackend
from projectq.meta import Control
from projectq.ops import Measure, Rz, H


def my_quantum_program(eng):
    qubit_0 = eng.allocate_qubit()
    control_qubit = eng.allocate_qubit()
    H | qubit_0
    H | control_qubit
    R2 = Rz(math.pi)
    with Control(eng, control_qubit):
        R2 | qubit_0
    H | control_qubit

    Measure | qubit_0
    Measure | control_qubit

    eng.flush()
    print("Qubit 0: {}".format(int(qubit_0)))
    print("Control: {}".format(int(control_qubit)))
    # To use get_probability you need to give a list of all the qubits
    # which determines the order of the bitstring.
    # qubit_0 is a list of one qubit and control_qubit is a list of 
    # one qubit, hence you can just use the +
    # Returns a dictionary with e.g. key '01' and value 0.22 which
    # means with 22% probability qubit_0 was in state 0 and the
    # control_qubit was in state 1
    print(eng.backend.get_probabilities(qubit_0 + control_qubit))


if __name__ == '__main__':
    eng = MainEngine(backend=IBMBackend(use_hardware=False, num_runs=100,
                     verbose=False, user="name@yahoo.com",
                     password="password"))
    my_quantum_program(eng)
```

**Comment by damiansteiger** [comment]
Did it solve your issues?

**Comment by erikweis** [comment]
Yes it did. Thank you!

**Comment by damiansteiger** [comment]
You are welcome
