### ISSUE TITLE
IBM device 'ibmqx5' not properly configured?

### ISSUE THREAD

**Issue by GiggleLiu** [ProjectQ-Framework/ProjectQ#188]
I can only access 5 out of 16 qubits on device 'ibmqx5'.
The following lines in file `projectq/cengines/_ibmcnotmapper.py` prevent me from doing this
```python
    places = list(range(5))
    ...
    ibm_order = [2, 1, 4, 0, 3]
```

It seems ProjectQ assume we have access to only 5 qubits on IBM cloud.

In fact, if I change it to
```python
    places = list(range(16))
    ...
    ibm_order = range(16)
```
I am able to access all 16 qubits on device 'ibmqx16'.

Here is the question,
1. why should we restrict the number of qubits to 5?
2. why we need the `ibm_order` variable?

**Comment by damiansteiger** [comment]
The _ibmcnotmapper.py is custom for the 5 qubit IBM chip with its connectivity and should not be used with another chip.

The default compiler for the 16 qubit IBM chip can be found here:
https://github.com/ProjectQ-Framework/ProjectQ/blob/develop/projectq/setups/ibm16.py
and an example here:
https://github.com/ProjectQ-Framework/ProjectQ/blob/develop/examples/ibm16.py

Currently if you want to run on the 16 qubit chip, you need to do the mapping manually. We will at some point add an automatic mapper for that chip as well.

**Comment by GiggleLiu** [comment]
@damiansteiger Thanks a lot! :+1:  

BTW, have you considered changing `import projectq.setups.ibm` to something like `projectq.setup('ibm')`? 

Because `import` itself is *doing something* is **not intuitive**. Moreover, it is **not safe** when you are trying to use different setups in a single program due to the python [import mechanism](https://stackoverflow.com/questions/3095071/in-python-what-happens-when-you-import-inside-of-a-function) (not friendly to new python programmer).

**Comment by damiansteiger** [comment]
Thanks for your feedback.

I agree. We have already thought about a few ways to improve the setups and decomposition rules. It will be a breaking change, so it will take us some time in order to improve everything at once.

If you currently want to use different setups at the same time, you can do so by explicitly importing and specifying the compiler `engine_list` instead of relying on the default parameter...
