### ISSUE TITLE
CommandModifier forwards unmodified command_list instead of modified command_list

### ISSUE THREAD

**Issue by Strilanc** [ProjectQ-Framework/ProjectQ#19]
def receive(self, command_list):
		...

		new_command_list = [self._cmd_mod_fun(cmd) for cmd in command_list]
                ^^^^^^^^^^^ unused

		self.send(command_list)

**Comment by thomashaener** [comment]
Thanks, good catch! It worked fine because the command modifiers modify cmd in-place, but if someone were to write a command modifier that returns a new command object, the list would indeed remain unmodified.
