### ISSUE TITLE
Decompositions of controlled-Ry and -Rx to controlled-Rz

### ISSUE THREAD

**Issue by kevinsung** [ProjectQ-Framework/ProjectQ#198]
I'm just wondering why the file `setups/decompositions/ry2rz.py` only registers a decomposition for rotations without control qubits:
```
def _recognize_RyNoCtrl(cmd):
    """ For efficiency reasons only if no control qubits."""
    return get_control_count(cmd) == 0
```
What are the "efficiency reasons"? I think it's desirable to have controlled-Ry and -Rx rotations to be decomposed to controlled-Rz first so we can use the dedicated controlled-Rz decomposition rather than the one for controlled- arbitrary rotation.

**Comment by damiansteiger** [comment]
Efficiency reason means less gates:
If I am not mistaken, then going first to Rz results in
C(Ry) = Rx C(Rz) Rx
And C(Rz) requires 2 CNOTs and 2 Rz (using our implemented rule) so in total 6 gates, whereas using the controlled arbitrary single qubit decomposition gives Ry CNOT Ry CNOT, so only 4 gates in total.

Also it helps avoiding potential/future circular loops in decompositions

I agree that for Rx, it depends if your hardware has a native Hadamard gate or not. Using the controlled arbitrary single qubit decomposition requires 3 Rz, 2 Ry and 2 CNOTs... Your proposal requires 2 Hadamard, 2 Rz, and 2 CNOT gates (hadamard gates require two rotation gates if they are not native)...

**Comment by kevinsung** [comment]
I see, that makes sense. Thanks!

**Comment by damiansteiger** [comment]
You are welcome
