### ISSUE TITLE
Probable error in TagRemover

### ISSUE THREAD

**Issue by Strilanc** [ProjectQ-Framework/ProjectQ#20]
Can't quite figure out what the intended action is, but the write to `cmd.tags` keeps being overwritten by future iterations in a way that looks suspicious.

		for cmd in command_list:
			for tag in self._tags:
				cmd.tags = [t for t in cmd.tags if not isinstance(t, tag)]
                                ^^^^^^^^^ only last iteration of loop matters
			self.send([cmd])

**Comment by thomashaener** [comment]
One could probably write this in a nicer way, similar to
```
for cmd in command_list:
    cmd.tags = [tag for tag in cmd.tags if not tag.__class__ in self._tags]
```
but this changes the behavior.

**Comment by Strilanc** [comment]
So the current behavior is intentional?

**Comment by damiansteiger** [comment]
Yes it is. It removes all tags (in cmd.tags) which are an instance of any of the classes in self._tags and does so for all commands in the command list.

**Comment by Strilanc** [comment]
Ooooh, I didn't catch the fact that cmd.tags was inside the list comprehension so the filtering effect was building up.
