### ISSUE TITLE
Measurements on trivial circuits should not fail in the IBMBackend

### ISSUE THREAD

**Issue by cgogolin** [ProjectQ-Framework/ProjectQ#259]
Consider the following minimal code:

```
import projectq as pq
from projectq.ops import Z, H, Measure, CNOT
from projectq import MainEngine
import projectq.setups.ibm

ibm_backend = pq.backends.IBMBackend(user='xxx', password='xxx', verbose=True)
eng = MainEngine(ibm_backend, engine_list=pq.setups.ibm.get_engine_list())

with pq.meta.Compute(eng):
    q1 = eng.allocate_qubit()
    Z | q1
    Z | q1
    Measure | q1
    eng.flush()
print("Measured: {}".format(int(q1)))
```
Instead of giving the expected result, it fails with the error:
```
Error: Can't access measurement result for qubit #0. The problem may be:
	1. Your code lacks a measurement statement
	2. You have not yet called engine.flush() to force execution of your code
	3. The underlying backend failed to register the measurement result
```
The problem seems to be that the `IBMBackend` simply does not preform a measurement (even when explicitly instructed to do so) on trivial circuits.

To convince yourself that nothing else with the above code is wrong, simply remove one of the `Z | q1` and it will run fine.

Please make `Measure` set the probabilities also for trivial circuits.

**Comment by damiansteiger** [comment]
Thanks for example, you are correct, there is a bug for the following code:
```
q1 = eng.allocate_qubit()
Measure | q1
eng.flush()
```

The QASM code generated is empty and hence does not get send to IBM. Therefore, when you later call Measure, it cannot give the result. We will fix this.

By the way, your circuit is invalid:

1. `with Compute` requires and `Uncompute` or `CustomUncompute`
2. Allocating qubits within `Compute` will require to manually delete the qubit
https://projectq.readthedocs.io/en/latest/projectq.meta.html#projectq.meta.Compute
3. `Compute` sections must be unitary, hence no measurements inside

We can add some more checks in future to catch some of these.

**Comment by cgogolin** [comment]
You are right, I forgot to remove the `with Compute` when stripping this down from a more verbose example.
