### ISSUE TITLE
Code coverage

### ISSUE THREAD

**Issue by damiansteiger** [ProjectQ-Framework/ProjectQ#26]
With the current settings of coveralls.io, code coverage can decrease if a function is refactored with less lines of code as before, see e.g. Pull request #15. This shouldn't be indicated as a possible failure. 

I haven't found a setting in coveralls.io to change to incremental code coverage reports. However, it is possible to check code coverage line by line on their website to check what is going on.

We might want to consider switching to a different tool, e.g. codecov which does handle such cases:
https://docs.codecov.io/docs/codecov-delta

**Comment by thomashaener** [comment]
I think it's fine as is.
