### ISSUE TITLE
Do not print "Waiting for results. [Job ID: ...]" when `verbose=False` on the IBMBackend

### ISSUE THREAD

**Issue by cgogolin** [ProjectQ-Framework/ProjectQ#269]
When using the IBMBackend the message `Waiting for results. [Job ID: ...]` is printed for each computation, even when `verbose=False`. This clutters the output of programs using ProjectQ.

**Comment by thomashaener** [comment]
Yes, but then we should also do at least one of the following
- add different levels of `verbose`
- expose the timeout
- catch Ctrl+C

So people who have been using Ctrl+C if a job is taking too long can then, e.g., adjust the timeout to a few seconds and still get the job id.
