### ISSUE TITLE
Improve automatic building of docs

### ISSUE THREAD

**Issue by damiansteiger** [ProjectQ-Framework/ProjectQ#280]
It would be great to fully automate the building of ProjectQ's docs using sphinx. Two tasks are currently done manually:

* [`autosummary`](https://github.com/ProjectQ-Framework/ProjectQ/blob/develop/docs/projectq.setups.decompositions.rst) part in the docs
* Automate the [docs of the decomposition rules](https://github.com/ProjectQ-Framework/ProjectQ/blob/develop/docs/projectq.setups.decompositions.rst)

**Comment by Abby3017** [comment]
I like to take up this task to automate the building of docs. Is it still available or the requirements are still same ??

**Comment by Takishima** [comment]
The task is still available and as far as I know, the requirements are the same. If you have suggestions on how to improve any aspect of it, feel free to discuss them here.

**Comment by Abby3017** [comment]
Thanks for letting me know. I will work on it and if some issue or suggestion is there, I will let you know.

**Comment by Abby3017** [comment]
Suggestions:

1.  This line is causing issue [conf.py](https://github.com/ProjectQ-Framework/ProjectQ/blob/develop/docs/conf.py#L384) as info is coming empty and `make clean html` is failing. I put a condition of `if not info['module']` to check if it is present then run the `eval`. Are you getting same error on running make command.
2. Can I create a dev_requirement.txt that have `sphinx sphinx_rtd_theme` as there requirements as it will be easy for someone else to install package in one go and make docs

Questions

1.  Can you clarify more about automate building of docs. Do you want something on [this line](https://github.com/syntaf/travis-sphinx).
2. Currently [both link](https://github.com/ProjectQ-Framework/ProjectQ/issues/280#issue-374490450) point to same url. On `make` command I was able to build it. I didn't have to do anything manually. Can you check that again or I missed something.

It would be great if you can answer these queries.

**Comment by Takishima** [comment]
Here are my answers to your suggestions/questions.

Suggestions:
1. According to the Sphinx [documentation](http://www.sphinx-doc.org/en/master/usage/extensions/linkcode.html) [1], if the domain is `py`, the `info` dictionary is guaranteed to contain both `'module'` and `'fullname'` keys, so I do not think that your check is needed. Maybe you could try making sure your sphinx is up-to-date?
2. I do not think this is necessary, people who want to build the ProjectQ documentation on their own should be able to manage that. Most users will never have to bother with these requirements anyway.

Questions:
1. ProjectQ is currently using [ReadTheDocs](https://readthedocs.org/) [2] to generate and host the documentation of the project. There is no plan at the moment to change that.
2. As #280 mentions, the two steps that are currently done manually is the generation of the `.. autosummary::` part of the `*.rst`files, as well as the `Submodules` part of the `decomposition.rst` file.

[1] http://www.sphinx-doc.org/en/master/usage/extensions/linkcode.html
[2] https://readthedocs.org
