### ISSUE TITLE
Restricted gate set allows any controlled single qubit operation

### ISSUE THREAD

**Issue by herr-d** [ProjectQ-Framework/ProjectQ#290]
When using the auto-replacer with a restricted gate set, controlled single qubit operations are also allowed.
I think this should not be allowed.

For example:

```
get_engine_list(one_qubit_gates=(HGate, XGate, YGate,
                              ZGate, TGate, Tdag, SGate, Sdag),
                two_qubit_gates=(CNOT,),
                other_gates=(TimeEvolution,))
```

This allows also controlled T-gates.

There is another thing I noticed: If I specify the TGate as an allowed one qubit gate it does not automatically include the invese of T.

**Comment by thomashaener** [comment]
Good catch, thanks!

We could add an additional parameter `include_inverses` or something similar.
