### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by dhirajmadan1** [ProjectQ-Framework/ProjectQ#292]
I am getting the foll. error with pip installation:-
pip install projectq
Collecting projectq
  Using cached https://files.pythonhosted.org/packages/95/59/1b2dfd77e1c4ed6cf18a320786f9c36cef2abeef2dc6f945d82cb9940fe6/projectq-0.4.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/wf/ccs_jbzd6vb3lw5hjpqn6nyh0000gn/T/pip-install-otn6q3l5/projectq/setup.py", line 12, in <module>
        long_description = open('README.rst').read()
      File "/anaconda/lib/python3.6/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 7095: ordinal not in range(128)
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/wf/ccs_jbzd6vb3lw5hjpqn6nyh0000gn/T/pip-install-otn6q3l5/projectq/

**Comment by thomashaener** [comment]
Could you try to `set PYTHONIOENCODING=utf-8` before installing?
