### ISSUE TITLE
problem installing projectq with python pip

### ISSUE THREAD

**Issue by tpmsjs** [ProjectQ-Framework/ProjectQ#293]
I'm trying to install  projectq with the following command:

python -m pip install projectq

I've used similar command for many other successful installs.

The projectq install fails, see message at the end of the output below

copying projectq\types\_qubit_test.py -> build\lib.win-amd64-3.7\projectq\types
    copying projectq\types\__init__.py -> build\lib.win-amd64-3.7\projectq\types
    creating build\lib.win-amd64-3.7\projectq\backends\_circuits
    copying projectq\backends\_circuits\_drawer.py -> build\lib.win-amd64-3.7\projectq\backends\_circuits
    copying projectq\backends\_circuits\_drawer_test.py -> build\lib.win-amd64-3.7\projectq\backends\_circuits
    copying projectq\backends\_circuits\_to_latex.py -> build\lib.win-amd64-3.7\projectq\backends\_circuits
    copying projectq\backends\_circuits\_to_latex_test.py -> build\lib.win-amd64-3.7\projectq\backends\_circuits
    copying projectq\backends\_circuits\__init__.py -> build\lib.win-amd64-3.7\projectq\backends\_circuits
    creating build\lib.win-amd64-3.7\projectq\backends\_ibm
    copying projectq\backends\_ibm\_ibm.py -> build\lib.win-amd64-3.7\projectq\backends\_ibm
    copying projectq\backends\_ibm\_ibm_http_client.py -> build\lib.win-amd64-3.7\projectq\backends\_ibm
    copying projectq\backends\_ibm\_ibm_http_client_test.py -> build\lib.win-amd64-3.7\projectq\backends\_ibm
    copying projectq\backends\_ibm\_ibm_test.py -> build\lib.win-amd64-3.7\projectq\backends\_ibm
    copying projectq\backends\_ibm\__init__.py -> build\lib.win-amd64-3.7\projectq\backends\_ibm
    creating build\lib.win-amd64-3.7\projectq\backends\_sim
    copying projectq\backends\_sim\_classical_simulator.py -> build\lib.win-amd64-3.7\projectq\backends\_sim
    copying projectq\backends\_sim\_classical_simulator_test.py -> build\lib.win-amd64-3.7\projectq\backends\_sim
    copying projectq\backends\_sim\_pysim.py -> build\lib.win-amd64-3.7\projectq\backends\_sim
    copying projectq\backends\_sim\_simulator.py -> build\lib.win-amd64-3.7\projectq\backends\_sim
    copying projectq\backends\_sim\_simulator_test.py -> build\lib.win-amd64-3.7\projectq\backends\_sim
    copying projectq\backends\_sim\__init__.py -> build\lib.win-amd64-3.7\projectq\backends\_sim
    creating build\lib.win-amd64-3.7\projectq\cengines\_replacer
    copying projectq\cengines\_replacer\_decomposition_rule.py -> build\lib.win-amd64-3.7\projectq\cengines\_replacer
    copying projectq\cengines\_replacer\_decomposition_rule_set.py -> build\lib.win-amd64-3.7\projectq\cengines\_replacer
    copying projectq\cengines\_replacer\_decomposition_rule_test.py -> build\lib.win-amd64-3.7\projectq\cengines\_replacer
    copying projectq\cengines\_replacer\_replacer.py -> build\lib.win-amd64-3.7\projectq\cengines\_replacer
    copying projectq\cengines\_replacer\_replacer_test.py -> build\lib.win-amd64-3.7\projectq\cengines\_replacer
    copying projectq\cengines\_replacer\__init__.py -> build\lib.win-amd64-3.7\projectq\cengines\_replacer
    creating build\lib.win-amd64-3.7\projectq\libs\math
    copying projectq\libs\math\_constantmath.py -> build\lib.win-amd64-3.7\projectq\libs\math
    copying projectq\libs\math\_constantmath_test.py -> build\lib.win-amd64-3.7\projectq\libs\math
    copying projectq\libs\math\_default_rules.py -> build\lib.win-amd64-3.7\projectq\libs\math
    copying projectq\libs\math\_gates.py -> build\lib.win-amd64-3.7\projectq\libs\math
    copying projectq\libs\math\_gates_test.py -> build\lib.win-amd64-3.7\projectq\libs\math
    copying projectq\libs\math\__init__.py -> build\lib.win-amd64-3.7\projectq\libs\math
    creating build\lib.win-amd64-3.7\projectq\libs\revkit
    copying projectq\libs\revkit\_control_function.py -> build\lib.win-amd64-3.7\projectq\libs\revkit
    copying projectq\libs\revkit\_control_function_test.py -> build\lib.win-amd64-3.7\projectq\libs\revkit
    copying projectq\libs\revkit\_permutation.py -> build\lib.win-amd64-3.7\projectq\libs\revkit
    copying projectq\libs\revkit\_permutation_test.py -> build\lib.win-amd64-3.7\projectq\libs\revkit
    copying projectq\libs\revkit\_phase.py -> build\lib.win-amd64-3.7\projectq\libs\revkit
    copying projectq\libs\revkit\_phase_test.py -> build\lib.win-amd64-3.7\projectq\libs\revkit
    copying projectq\libs\revkit\_utils.py -> build\lib.win-amd64-3.7\projectq\libs\revkit
    copying projectq\libs\revkit\__init__.py -> build\lib.win-amd64-3.7\projectq\libs\revkit
    creating build\lib.win-amd64-3.7\projectq\setups\decompositions
    copying projectq\setups\decompositions\arb1qubit2rzandry.py -> build\lib.win-amd64-3.7\projectq\setups\decompositions
    copying projectq\setups\decompositions\arb1qubit2rzandry_test.py -> build\lib.win-amd64-3.7\projectq\setups\decompositions
    copying projectq\setups\decompositions\barrier.py -> build\lib.win-amd64-3.7\projectq\setups\decompositions
    copying projectq\setups\decompositions\barrier_test.py -> build\lib.win-amd64-3.7\projectq\setups\decompositions
    copying projectq\setups\decompositions\carb1qubit2cnotrzandry.py -> build\lib.win-amd64-3.7\projectq\setups\decompositions
    copying projectq\setups\decompositions\carb1qubit2cnotrzandry_test.py -> build\lib.win-amd64-3.7\projectq\setups\decompositions
    copying projectq\setups\decompositions\cnot2cz.py -> build\lib.win-amd64-3.7\projectq\setups\decompositions
    copying projectq\setups\decompositions\cnot2cz_test.py -> build\lib.win-amd64-3.7\projectq\setups\decompositions
    copying projectq\setups\decompositions\cnu2toffoliandcu.py -> build\lib.win-amd64-3.7\projectq\setups\decompositions
    copying projectq\setups\decompositions\cnu2toffoliandcu_test.py -> build\lib.win-amd64-3.7\projectq\setups\decompositions
    copying projectq\setups\decompositions\crz2cxandrz.py -> build\lib.win-amd64-3.7\projectq\setups\decompositions
    copying projectq\setups\decompositions\entangle.py -> build\lib.win-amd64-3.7\projectq\setups\decompositions
    copying projectq\setups\decompositions\globalphase.py -> build\lib.win-amd64-3.7\projectq\setups\decompositions
    copying projectq\setups\decompositions\ph2r.py -> build\lib.win-amd64-3.7\projectq\setups\decompositions
    copying projectq\setups\decompositions\qft2crandhadamard.py -> build\lib.win-amd64-3.7\projectq\setups\decompositions
    copying projectq\setups\decompositions\qubitop2onequbit.py -> build\lib.win-amd64-3.7\projectq\setups\decompositions
    copying projectq\setups\decompositions\qubitop2onequbit_test.py -> build\lib.win-amd64-3.7\projectq\setups\decompositions
    copying projectq\setups\decompositions\r2rzandph.py -> build\lib.win-amd64-3.7\projectq\setups\decompositions
    copying projectq\setups\decompositions\rx2rz.py -> build\lib.win-amd64-3.7\projectq\setups\decompositions
    copying projectq\setups\decompositions\rx2rz_test.py -> build\lib.win-amd64-3.7\projectq\setups\decompositions
    copying projectq\setups\decompositions\ry2rz.py -> build\lib.win-amd64-3.7\projectq\setups\decompositions
    copying projectq\setups\decompositions\ry2rz_test.py -> build\lib.win-amd64-3.7\projectq\setups\decompositions
    copying projectq\setups\decompositions\sqrtswap2cnot.py -> build\lib.win-amd64-3.7\projectq\setups\decompositions
    copying projectq\setups\decompositions\sqrtswap2cnot_test.py -> build\lib.win-amd64-3.7\projectq\setups\decompositions
    copying projectq\setups\decompositions\stateprep2cnot.py -> build\lib.win-amd64-3.7\projectq\setups\decompositions
    copying projectq\setups\decompositions\stateprep2cnot_test.py -> build\lib.win-amd64-3.7\projectq\setups\decompositions
    copying projectq\setups\decompositions\swap2cnot.py -> build\lib.win-amd64-3.7\projectq\setups\decompositions
    copying projectq\setups\decompositions\time_evolution.py -> build\lib.win-amd64-3.7\projectq\setups\decompositions
    copying projectq\setups\decompositions\time_evolution_test.py -> build\lib.win-amd64-3.7\projectq\setups\decompositions
    copying projectq\setups\decompositions\toffoli2cnotandtgate.py -> build\lib.win-amd64-3.7\projectq\setups\decompositions
    copying projectq\setups\decompositions\uniformlycontrolledr2cnot.py -> build\lib.win-amd64-3.7\projectq\setups\decompositions
    copying projectq\setups\decompositions\uniformlycontrolledr2cnot_test.py -> build\lib.win-amd64-3.7\projectq\setups\decompositions
    copying projectq\setups\decompositions\_gates_test.py -> build\lib.win-amd64-3.7\projectq\setups\decompositions
    copying projectq\setups\decompositions\__init__.py -> build\lib.win-amd64-3.7\projectq\setups\decompositions
    running build_ext
    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Users\Thomas\AppData\Local\Continuum\miniconda3\include -IC:\Users\Thomas\AppData\Local\Continuum\miniconda3\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\winrt" /EHsc /TpC:\Users\Thomas\AppData\Local\Temp\tmp0ohbyqhv.cpp /FoUsers\Thomas\AppData\Local\Temp\tmp0ohbyqhv.obj
    tmp0ohbyqhv.cpp
    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Users\Thomas\AppData\Local\Continuum\miniconda3\include -IC:\Users\Thomas\AppData\Local\Continuum\miniconda3\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\winrt" /EHsc /TpC:\Users\Thomas\AppData\Local\Temp\tmpqh725s_v.cpp /FoUsers\Thomas\AppData\Local\Temp\tmpqh725s_v.obj -fopenmp
    cl : Command line warning D9002 : ignoring unknown option '-fopenmp'
    tmpqh725s_v.cpp
    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Users\Thomas\AppData\Local\Continuum\miniconda3\include -IC:\Users\Thomas\AppData\Local\Continuum\miniconda3\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\winrt" /EHsc /TpC:\Users\Thomas\AppData\Local\Temp\tmpv_gqrkk7.cpp /FoUsers\Thomas\AppData\Local\Temp\tmpv_gqrkk7.obj -march=native
    cl : Command line warning D9002 : ignoring unknown option '-march=native'
    tmpv_gqrkk7.cpp
    building 'projectq.backends._sim._cppsim' extension
    creating build\temp.win-amd64-3.7
    creating build\temp.win-amd64-3.7\Release
    creating build\temp.win-amd64-3.7\Release\projectq
    creating build\temp.win-amd64-3.7\Release\projectq\backends
    creating build\temp.win-amd64-3.7\Release\projectq\backends\_sim
    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Users\Thomas\AppData\Local\Continuum\miniconda3\Include -IC:\Users\Thomas\AppData\Roaming\Python\Python37\Include -IC:\Users\Thomas\AppData\Local\Continuum\miniconda3\include -IC:\Users\Thomas\AppData\Local\Continuum\miniconda3\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\winrt" /EHsc /Tpprojectq/backends/_sim/_cppsim.cpp /Fobuild\temp.win-amd64-3.7\Release\projectq/backends/_sim/_cppsim.obj /EHsc -DINTRIN /arch:AVX  /DVERSION_INFO=\"0.4.1\"
    _cppsim.cpp
    c:\users\thomas\appdata\local\continuum\miniconda3\include\pybind11\detail/common.h(71): fatal error C1189: #error:  pybind11 requires MSVC 2015 update 3 or newer
    Traceback (most recent call last):
      File "C:\Users\Thomas\AppData\Local\Continuum\miniconda3\lib\distutils\_msvccompiler.py", line 423, in compile
        self.spawn(args)
      File "C:\Users\Thomas\AppData\Local\Continuum\miniconda3\lib\distutils\_msvccompiler.py", line 542, in spawn
        return super().spawn(cmd)
      File "C:\Users\Thomas\AppData\Local\Continuum\miniconda3\lib\distutils\ccompiler.py", line 909, in spawn
        spawn(cmd, dry_run=self.dry_run)
      File "C:\Users\Thomas\AppData\Local\Continuum\miniconda3\lib\distutils\spawn.py", line 38, in spawn
        _spawn_nt(cmd, search_path, dry_run=dry_run)
      File "C:\Users\Thomas\AppData\Local\Continuum\miniconda3\lib\distutils\spawn.py", line 81, in _spawn_nt
        "command %r failed with exit status %d" % (cmd, rc))
    distutils.errors.DistutilsExecError: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit status 2

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Users\Thomas\AppData\Local\Temp\pip-install-hzxq3ntq\projectq\setup.py", line 146, in build_extensions
        build_ext.build_extensions(self)
      File "C:\Users\Thomas\AppData\Local\Continuum\miniconda3\lib\site-packages\Cython\Distutils\old_build_ext.py", line 194, in build_extensions
        self.build_extension(ext)
      File "C:\Users\Thomas\AppData\Local\Continuum\miniconda3\lib\site-packages\setuptools\command\build_ext.py", line 199, in build_extension
        _build_ext.build_extension(self, ext)
      File "C:\Users\Thomas\AppData\Local\Continuum\miniconda3\lib\distutils\command\build_ext.py", line 533, in build_extension
        depends=ext.depends)
      File "C:\Users\Thomas\AppData\Local\Continuum\miniconda3\lib\distutils\_msvccompiler.py", line 425, in compile
        raise CompileError(msg)
    distutils.errors.CompileError: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit status 2

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Thomas\AppData\Local\Temp\pip-install-hzxq3ntq\projectq\setup.py", line 171, in <module>
        packages=find_packages()
      File "C:\Users\Thomas\AppData\Local\Continuum\miniconda3\lib\site-packages\setuptools\__init__.py", line 140, in setup
        return distutils.core.setup(**attrs)
      File "C:\Users\Thomas\AppData\Local\Continuum\miniconda3\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "C:\Users\Thomas\AppData\Local\Continuum\miniconda3\lib\distutils\dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "C:\Users\Thomas\AppData\Local\Continuum\miniconda3\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\Thomas\AppData\Local\Continuum\miniconda3\lib\site-packages\setuptools\command\install.py", line 61, in run
        return orig.install.run(self)
      File "C:\Users\Thomas\AppData\Local\Continuum\miniconda3\lib\distutils\command\install.py", line 545, in run
        self.run_command('build')
      File "C:\Users\Thomas\AppData\Local\Continuum\miniconda3\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\Users\Thomas\AppData\Local\Continuum\miniconda3\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\Thomas\AppData\Local\Continuum\miniconda3\lib\distutils\command\build.py", line 135, in run
        self.run_command(cmd_name)
      File "C:\Users\Thomas\AppData\Local\Continuum\miniconda3\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\Users\Thomas\AppData\Local\Continuum\miniconda3\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\Thomas\AppData\Local\Continuum\miniconda3\lib\site-packages\setuptools\command\build_ext.py", line 78, in run
        _build_ext.run(self)
      File "C:\Users\Thomas\AppData\Local\Continuum\miniconda3\lib\site-packages\Cython\Distutils\old_build_ext.py", line 186, in run
        _build_ext.build_ext.run(self)
      File "C:\Users\Thomas\AppData\Local\Continuum\miniconda3\lib\distutils\command\build_ext.py", line 339, in run
        self.build_extensions()
      File "C:\Users\Thomas\AppData\Local\Temp\pip-install-hzxq3ntq\projectq\setup.py", line 148, in build_extensions
        self.warning("")
      File "C:\Users\Thomas\AppData\Local\Temp\pip-install-hzxq3ntq\projectq\setup.py", line 151, in warning
        raise Exception(warning_text + "\nCould not install the C++-Simulator."
    Exception:
    Could not install the C++-Simulator.
    ProjectQ will default to the (slow) Python simulator.
    Use --without-cppsimulator to skip building the (faster) C++ version of the simulator.

    ----------------------------------------
Command "C:\Users\Thomas\AppData\Local\Continuum\miniconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Thomas\\AppData\\Local\\Temp\\pip-install-hzxq3ntq\\projectq\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\Thomas\AppData\Local\Temp\pip-record-xfazekvh\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\Thomas\AppData\Local\Temp\pip-install-hzxq3ntq\projectq\

**Comment by thomashaener** [comment]
Please try updating your C/C++ compiler. The error message above says `#error: pybind11 requires MSVC 2015 update 3 or newer`

**Comment by thomashaener** [comment]
Closing this issue. Please feel free to reopen if you need further assistance.
