### ISSUE TITLE
Noise simulation

### ISSUE THREAD

**Issue by Coxious** [ProjectQ-Framework/ProjectQ#310]
Hi,

I've noticed in https://arxiv.org/pdf/1612.08091.pdf that ProjectQ is developing stochastic noise models and high-performance density matrix simulator, any progress now?

**Comment by damiansteiger** [comment]
Hi,

Some users have built their own stochastic noise simulation into ProjectQ using the existing simulator (However, I am not aware it is open sourced). But we haven't worked on it because other features had more user requests. Same for the density matrix simulator.

**Comment by Coxious** [comment]
Thanks for the reply!
