### ISSUE TITLE
Cannot find control qubits 

### ISSUE THREAD

**Issue by DrissiReda** [ProjectQ-Framework/ProjectQ#313]
I cannot find the control qubits inside the cmd object here is a minimal code to reproduce the issue:

```python
from projectq import MainEngine
from projectq.meta import get_control_count
from projectq.ops import X, NOT, C
from pprint import pprint
class Testing(MainEngine):
    def __init__(self):
        MainEngine.__init__(self)
    def receive(self, cmdlist):
        for cmd in cmdlist:
            if cmd.gate == NOT:
                print("control size is {}".format(get_control_count(cmd)))
                print(cmd.control_qubits)
                pprint(vars(cmd))


if __name__ == "__main__":
    eng = Testing()
    q = eng.allocate_qureg(3)
    C(X, n=2) | (q[0], q[1], q[2])
```

The output is : 

```bash
control size is 0
[]
{'_control_qubits': [],
 '_engine': <__main__.Testing object at 0x7fec595d67f0>,
 '_qubits': ([<projectq.types._qubit.WeakQubitRef object at 0x7fec42108208>],),
 'gate': <projectq.ops._gates.XGate object at 0x7fec4bf00a58>,
 'tags': []}
```
Aren't the control qubits supposed to be in the `_control_qubits` list? The only qubits I can find are the target qubits inside the `_qubits` list

**Comment by Takishima** [comment]
The control qubits are only added to the command after it is received by the `ControlEngine` further down the chain after the `MainEngine`. For implementation details see “3.2.1 Implementation of meta instructions” in https://doi.org/10.3929/ethz-b-000322770.

To implement a testing engine such as yours, that can be used to check that indeed control qubits are added right after the `MainEngine`, you could do the following:

```
test_eng = Testing(BasicEngine) # Or CommandPrinter
eng = projectq.MainEngine(engine_list=[test_eng])
```

**Comment by DrissiReda** [comment]
Thank you, that is important information, but I cannot use `MainEngine` since I want to create a class that inherits from it and adds a few functions, using your method prevents me from getting these functions.

**Comment by Takishima** [comment]
That's perfectly normal, your version of ProjectQ does not have these gates yet.

For the other things, I would suggest opening a new issue and describe in more details what you are trying to achieve. Otherwise it is hard to help.
