### ISSUE TITLE
Error in the implementation of the QFT?

### ISSUE THREAD

**Issue by EliasCombarro** [ProjectQ-Framework/ProjectQ#319]
Hi,

I am a little confused with the QFT gate provided in ProjectQ. I have tried the following:

import projectq
from projectq.ops import QFT, All, Measure, X, get_inverse

eng = projectq.MainEngine()
q = eng.allocate_qureg(2)

X | q[0]

eng.flush()  

for val in ['00','01','10','11']:
    amp = eng.backend.get_amplitude(val,q)
    print(val,amp)  

QFT | q

eng.flush()

for val in ['00','01','10','11']:
    amp = eng.backend.get_amplitude(val,q)
    print(val,amp)

All(Measure) | q    

which gives the following output:

00 0j
01 0j
10 (1+0j)
11 0j
00 (0.4999999999999999+0j)
01 (-5.1705776777553605e-14+0.4999999999999999j)
10 (-0.4999999999999999+0j)
11 (5.1705776777553605e-14-0.4999999999999999j)

If I am not mistaken, this would imply that the term for [10,10] on the matrix would be -1/2, but there is NO term in the diagonal of the QFT matrix of size 4x4 which is negative!!! 

What am I doing wrong?

Thank you very much in advance.

Elías

**Comment by Takishima** [comment]
Did you take into account that the QFT in ProjectQ does not implement the final swaps ?

See: https://projectq.readthedocs.io/en/latest/projectq.setups.decompositions.html#module-projectq.setups.decompositions.qft2crandhadamard

**Comment by EliasCombarro** [comment]
Yes, I did notice that a few days ago and that solves my problem. Thank you.
