### ISSUE TITLE
Example get probabilities on IBM Backend

### ISSUE THREAD

**Issue by jason-jk-kang** [ProjectQ-Framework/ProjectQ#321]
Hi,

I have a hamiltonian which I am trying to calculate the expected value of through the IBM simulator. Since there is no get_expectation function for the ibm engine, I am using get_probabilities and will then calculate the expected value manually.

I first generate a wavefunction and initialize the registers, then I build the circuit and act it on the wavefunction. Finally, I flush my circuit.

When I call get_probabilities on my backend, I get the error

```
  File "probabilities_test.py", line 41, in energy_objective
    results = compiler_engine.backend.get_probabilities(wavefunction)
  File "/home/jasonkang/anaconda3/lib/python3.7/site-packages/projectq/backends/_ibm/_ibm.py", line 222, in get_probabilities
    mapped_state[i] = state[self._logical_to_physical(qureg[i].id)]
  File "/home/jasonkang/anaconda3/lib/python3.7/site-packages/projectq/backends/_ibm/_ibm.py", line 181, in _logical_to_physical
    assert self.main_engine.mapper is not None
```

Could somebody help me debug this? The example that I am working off of can be found here
https://github.com/ProjectQ-Framework/ProjectQ/issues/218

**Comment by Takishima** [comment]
Could you post the whole code you are running?

From looking at the error message, it seems like there is no mapper present in the compiler engine list, which is why you get the assertion error.

**Comment by Takishima** [comment]
Closing inactive issue. Please reopen if required.
