### ISSUE TITLE
pybind11 dependancy in pip3 install ProjectQ not satisfied

### ISSUE THREAD

**Issue by twobombs** [ProjectQ-Framework/ProjectQ#323]
I'm working on a Dockerized Qrack-ProjectQ-SimulaQron container and found that the requirements for the pip3 install projectq missed the pybind11 dependancy:

![Screenshot 2019-04-15 at 14 44 15](https://user-images.githubusercontent.com/12692227/56136315-d54d7d00-5f92-11e9-86b0-51750e47ad6f.png)

installing pybind11 before installing ProjectQ fixes this:

![Screenshot 2019-04-15 at 15 24 10](https://user-images.githubusercontent.com/12692227/56136371-f31ae200-5f92-11e9-977a-85248b65361c.png)

So methinks adding pybind11 as a requirement for the correct installation of ProjectQ is in place IMHO.

**Comment by Takishima** [comment]
Which pip version are you currently using ?
`pybind11` is actually listed as a requirements for ProjectQ (take a look at the requirements.txt) file.

**Comment by twobombs** [comment]
Hi Takishima, thank you for responding.

> pybind11 is actually listed as a requirements for ProjectQ (take a look at the requirements.txt) file.

Indeed: that what is so strange about this situation. As though the requirements.txt is ignored at that point. Pip3 is v9.01

<img width="486" alt="Screenshot 2019-04-16 at 12 23 00" src="https://user-images.githubusercontent.com/12692227/56202071-8d862e80-6042-11e9-9879-89947ba41de0.png">

However: I do pull a fork of your project in that Dockerfile ( https://github.com/vm6502q/ProjectQ ) but that one also has the pybind11 as a requirement in the txt file, I see no differences at that point.

**Comment by twobombs** [comment]
I see this as a framework weirdness, outside the scope of ProjectQ. 

Closing
