### ISSUE TITLE
Is the Documentation site being updated?

### ISSUE THREAD

**Issue by fernandodelaiglesia** [ProjectQ-Framework/ProjectQ#325]
Dear friends,

I entered in the Documentation site for the project (https://projectq.readthedocs.io/en/latest/) and I noticed that the documentation in the branch "develop" for the Phase Estimation gate is not present (https://projectq.readthedocs.io/en/develop/projectq.setups.decompositions.html).

So my questions are: Is this site being updated with the branches in github? Did I fail in creating the documentation files for Phase Estimation (in docs/projectq.ops.rst)?

Thanks a lot
Best

**Comment by Takishima** [comment]
Related to #280
