### ISSUE TITLE
Can not connect to IMBQ

### ISSUE THREAD

**Issue by ozlemsalehi** [ProjectQ-Framework/ProjectQ#347]
When making requests in _ibm_http_client file such as in the method authenticate, it is returning an html file, not a json file which is throwing exceptions. The reason might be that the api links are not working no more.

**Comment by dbretaud** [comment]
I just took a look at the Qiskit documentation, it seems indeed that since last month the old API is not working anymore:
https://github.com/Qiskit/qiskit-ibmq-provider#updating-to-the-new-ibm-q-experience

**Comment by ozlemsalehi** [comment]
Yes and they didn't include a new link for connecting to backend. They describe it only in the case of using qiskit.
