### ISSUE TITLE
Example get probabilities on IBM Backend

### ISSUE THREAD

**Issue by quantum-rookie** [ProjectQ-Framework/ProjectQ#363]

**Comment by quantum-rookie** [comment]
I tried to run this example in pycharm， but after a while, it doesn't work, what happened?
![image](https://user-images.githubusercontent.com/63296937/79204334-faf3b780-7e6e-11ea-8256-f1865d284589.png)

**Comment by Takishima** [comment]
Hi,

What versions of Python, pip and ProjectQ are you currently using?
Also, do you get any error/warning messages? If yes, could you please provide them?

**Comment by quantum-rookie** [comment]
Hi,

Python 3.7, pip 20.0.2, ProjectQ 0.5.0
there is no any error/warning messages, just like this..


![image](https://user-images.githubusercontent.com/63296937/79230894-da8c2300-7e97-11ea-87f1-caaff67c343e.png)

**Comment by quantum-rookie** [comment]
eng = MainEngine(IBMBackend(use_hardware=True, toke=token, num_runs=1024, verbose=False, device=device))
Should i add IBM account and password to this code?  such as: user='***', password='***'.

**Comment by dbretaud** [comment]
could you run your code with verbose=True?

**Comment by quantum-rookie** [comment]
no,  there is no any change . all examples about IBM as backend are useless, i don't know why.

**Comment by dbretaud** [comment]
the fact we don't see even 'IBM Q token> ' makes me think it's just a prompt issue.  (also little bug: your MainEngine is defined only if device is None). Try to run it by replacing the prompts by your IBMQ token and the device you want to run it with.

**Comment by dbretaud** [comment]
Anyway, seems IBMQ already upgraded their job submission mechanism; submitting circuits (what we were doing) via the POST method is getting deprecated:
https://github.com/Qiskit/qiskit-ibmq-provider/commit/e33b17ad260f86bdefd27e4e72f7fb2083719f69

**Comment by quantum-rookie** [comment]
ok

**Comment by quantum-rookie** [comment]
hi,  i typed token and device. i got  result of  the example in IBM quantum Experience. python 3.7, pip 20.02, projectq 0.5.0. but in pycharm, there are some errors:

D:\anaconda\python.exe C:/Users/xkdr/.PyCharm2019.3/config/scratches/scratch_1.py
- Failed to parse response:
'qObjectResult'
Traceback (most recent call last):
  File "C:/Users/xkdr/.PyCharm2019.3/config/scratches/scratch_1.py", line 26, in <module>
    print(run_entangle(eng))
  File "C:/Users/xkdr/.PyCharm2019.3/config/scratches/scratch_1.py", line 13, in run_entangle
    eng.flush()
  File "D:\anaconda\lib\site-packages\projectq\cengines\_main.py", line 304, in flush
    self.receive([Command(self, FlushGate(), ([WeakQubitRef(self, -1)],))])
  File "D:\anaconda\lib\site-packages\projectq\cengines\_main.py", line 266, in receive
    self.send(command_list)
  File "D:\anaconda\lib\site-packages\projectq\cengines\_main.py", line 288, in send
    raise compact_exception  # use verbose=True for more info
Exception: Failed to run the circuit. Aborting.
 raised in:
'  File "D:\\anaconda\\lib\\site-packages\\projectq\\backends\\_ibm\\_ibm.py", line 323, in _run'
'    raise Exception("Failed to run the circuit. Aborting.")'

Process finished with exit code 1

code:
import projectq.setups.ibm
from projectq.backends import IBMBackend
from projectq.ops import Measure, Entangle, All
from projectq import MainEngine

def run_entangle(eng, num_qubits=4):
    qureg = eng.allocate_qureg(num_qubits)

    Entangle | qureg

    All(Measure) | qureg

    eng.flush()

    results = eng.backend.get_probabilities(qureg)
    for state in results:
        print("Measured {} with p = {}.".format(state, results[state]))
    return [int(q) for q in qureg]

if __name__ == "__main__":
    eng = MainEngine(IBMBackend(use_hardware=True,
                                
token='d8eec149cc158500f72eb4445fe6c10acb353c799829e47bfaac4ddd378ba1d75bd29e06a753a92c6e63d46427e64ff32304c22405caa162b6a5c1aae898ba1e', num_runs=523,
                                verbose=False, device='ibmq_london'),
                     engine_list=projectq.setups.ibm.get_engine_list(device='ibmq_london',
                                                                     token='d8eec149cc158500f72eb4445fe6c10acb353c799829e47bfaac4ddd378ba1d75bd29e06a753a92c6e63d46427e64ff32304c22405caa162b6a5c1aae898ba1e'))
    print(run_entangle(eng))
