### ISSUE TITLE
Controlled tensors work inconsistently w.r.t. non-controlled tensors

### ISSUE THREAD

**Issue by Strilanc** [ProjectQ-Framework/ProjectQ#37]
When you apply:

    All(X) | targets

The engine receives X commands via the __or__ implementation in Tensor.

But if you apply:

    C(All(X)) | (control, targets)

Then then the __or__ operation is bypassed and the engine receives a Tensor command instead.

**Comment by Strilanc** [comment]
I believe the fix here is to replace `generate_command` with `generate_commands`, fix up any existing usage to deal with the multiplicity, and always always have `__or__` delegate to `generate_commands`.

**Comment by damiansteiger** [comment]
Good catch. I will have a look at it

**Comment by damiansteiger** [comment]
This is addressed in #53
