### ISSUE TITLE
The code of QPE.

### ISSUE THREAD

**Issue by quantum-rookie** [ProjectQ-Framework/ProjectQ#372]
hello， I want to know the specific code representation of the quantum phase estimation gate.

**Comment by Takishima** [comment]
You can see the code for the gate in the corresponding decomposition rule. You can find it in the following file: `projectq/setups/decompositions/phaseestimation.py`

**Comment by quantum-rookie** [comment]
Hi, i know this file.  i've seen this before.  i don't know how to realize the square root of U(It's acting on the qubits of the system ), the fourth square root of U on projectq.
![image](https://user-images.githubusercontent.com/63296937/83880842-66248080-a772-11ea-849e-673d6707dd7e.png)
