### ISSUE TITLE
Version 0.6.1 crashes on Linux

### ISSUE THREAD

**Issue by cqc-alec** [ProjectQ-Framework/ProjectQ#406]
With Ubuntu 20.04, x86_64, Python 3.8.5, projectq 0.6.1:

```
$ python -c "from projectq import MainEngine; MainEngine()"
Illegal instruction (core dumped)
```

**Comment by Takishima** [comment]
Well that's not something that I wanted to see the day after the update...

It seems this is due to the new binary wheels that were introduced. I will pull those for now until I can figure out what is wrong.
In any case, thanks for bringing this issue up.

**Comment by cqc-alec** [comment]
> I have pushed a new post-version `v0.6.1.post0` that is source-only and I will pull the existing `v0.6.1` from Pypi later today.

Thanks! The post-version seems to work well.
