### ISSUE TITLE
Probability distribution of qubits' classical value

### ISSUE THREAD

**Issue by Luigi2898** [ProjectQ-Framework/ProjectQ#413]
Why in the simulator there isn't an equivalent to `get_probabilities()` (like in IBM backend)? Wouldn't it be great to have something like this?

**Comment by Takishima** [comment]
While there is indeed no functions that can give you the data you want immediately, the simulator does provide a [`get_probability()`](https://projectq.readthedocs.io/en/latest/_doc_gen/projectq.backends.html#projectq.backends.Simulator.get_probability) method to access the probability of a particular bit string.

If you want to have the complete set of probabilities, you can do something like this:

```python
probabilities = {}
n_qubits = len(qureg)
for i in range(n_qubits):
    bit_string = '{0:b}'.format(i)
    probabilities[bit_string] = eng.backend.get_probability(bit_string, qureg)
```

**Comment by Luigi2898** [comment]
Thanks a lot for your disponibility! 😊
