### ISSUE TITLE
How to check if projectq is running on C++ Simulator

### ISSUE THREAD

**Issue by keithyau** [ProjectQ-Framework/ProjectQ#415]
Hi there, 

I'm trying to run ProjectQ on ARM devices and since the LLVM / GCC is well supported. How do i check if the jobs are not running on Python Simulator?

Thank you very mcuh !!!

**Comment by Takishima** [comment]
The Python simulator always print a message upon construction `(Note: This is the (slow) Python simulator.)`.

If that message does not appear when creating a new `Simulator`  object, you're using the C++ simulator.

**Comment by keithyau** [comment]
hi, i found that pybind11 is not really working and pip install not compiling .so

But python3 setup.py build install works.

**Comment by Takishima** [comment]
Could you provide here the full installation log with the error when running the installation command using Pip?

Something like `python3 -m pip install -v projectq`.

**Comment by keithyau** [comment]
MacOS Big sur
git clone
python3 -m pip install --user .  #No error messages but .so not generated

python3 setup.py install #.so generated with ERROR 
![image](https://user-images.githubusercontent.com/659311/135060403-7ecd6819-5573-413e-a7be-e916b5e3ad95.png)


AWS gravtion ARM machine
git clone 
python3 -m pip install --user .  #No error messages but .so not generated
python3 setup.py install #.so generated without ERROR 
![image](https://user-images.githubusercontent.com/659311/135060597-3dde85d9-1726-422e-a009-cf1a689b3948.png)

But run sample code below cannot mutli-thread
import os
os.environ["OMP_NUM_THREADS"] = '4'
os.environ["OMP_PROC_BIND"] = "spread"

from projectq import MainEngine
from projectq.backends import ResourceCounter
from projectq.ops import All, CNOT, H, Measure, Rz, X, Z, Swap
from projectq.ops import QFT
from projectq.setups import linear
from projectq.setups.default import get_engine_list

import time
start_time = time.time()
compiler_engines = linear.get_engine_list(num_qubits=100,
                                          one_qubit_gates='any',
                                          two_qubit_gates=(CNOT, Swap))
resource_counter = ResourceCounter()
#eng = MainEngine(engine_list=get_engine_list() + [resource_counter])
eng = MainEngine(backend=resource_counter, engine_list=compiler_engines)
#eng = MainEngine(backend=resource_counter)
qureg = eng.allocate_qureg(100)
QFT | qureg
eng.flush()

print(resource_counter)
print("--- %s seconds ---" % (time.time() - start_time))


![image](https://user-images.githubusercontent.com/659311/135060859-73946847-17d7-4845-b1e1-6a6842a45934.png)



thank you so much

**Comment by Takishima** [comment]
Thanks for the information.

One potential issue regarding the multi-threading is that the Apple Clang compiler does not actually support OpenMP (haven't checked lately), so you might want to install the ` llvm` package using HomeBrew (for e.g.) and then install ProjectQ like so:

```
CC=/usr/local/opt/llvm/bin/clang CXX=/usr/local/opt/llvm/bin/clang++ python3 -m pip install -v projectq
```

**Comment by Takishima** [comment]
Also, regarding your second point about multi-threading, only the C++ simulator is actually capable of using OpenMP enabled code. So all of these:

```
eng = MainEngine(backend=resource_counter, engine_list=compiler_engines)
eng = MainEngine(backend=resource_counter)
```

Will not run in parallel, since no C++ simulator is instantiated.

**Comment by keithyau** [comment]
> Also, regarding your second point about multi-threading, only the C++ simulator is actually capable of using OpenMP enabled code. So all of these:
> 
> ```
> eng = MainEngine(backend=resource_counter, engine_list=compiler_engines)
> eng = MainEngine(backend=resource_counter)
> ```
> 
> Will not run in parallel, since no C++ simulator is instantiated.

So how can I run the C++ Simulator ?

**Comment by keithyau** [comment]
> > Also, regarding your second point about multi-threading, only the C++ simulator is actually capable of using OpenMP enabled code. So all of these:
> > ```
> > eng = MainEngine(backend=resource_counter, engine_list=compiler_engines)
> > eng = MainEngine(backend=resource_counter)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Will not run in parallel, since no C++ simulator is instantiated.
> 
> So how can I run the C++ Simulator ?

Worked with demo Shor algo, Thank you so much !
