### ISSUE TITLE
not work on macbook  with M1 Chip

### ISSUE THREAD

**Issue by big91987** [ProjectQ-Framework/ProjectQ#418]
Hi everyone，
I got a crash of projectq lib on macbook with M1 Chip , is there any solution for this chip？thx

(venv) ➜  test git:(master) ✗ python3 ./test1.py
**[1]    40975 illegal hardware instruction  python3 ./test1.py**
(venv) ➜  test git:(master) ✗ cat test1.py
from projectq import MainEngine # import the main compiler engine
from projectq.ops import H, Measure # import the operations we want to perform␣

qengine = MainEngine() # create a default compiler (the back-end is a simulator)
qubit = qengine.allocate_qubit() # allocate 1 qubit
H | qubit # apply a Hadamard gate
Measure | qubit # measure the qubit
qengine.flush() # flush all gates (and execute measurements)
print("Output {}".format(int(qubit))) # output measurement result%

**Comment by Takishima** [comment]
Mmm this is weird, the current `setup.py` should be able to compile the C++ version of the simulator without AVX2 intrinsics.

Could you please provide the full log of the installation?

Something like this:
```bash
python3 -m pip install -v projectq
```

**Comment by Takishima** [comment]
@CalMacCQ Could you try giving me the full log of the following command:

```bash
python3 -m pip install -v projectq
```

**Comment by CalMacCQ** [comment]
Hi,
 Thanks for getting back to me. the output of the command was very long so I've written it to a txt file using
 `python3 -m pip install -v projectq > pq_log.txt`
 
 Hope this helps. Possible I'm just missing something.
[pq_log.txt](https://github.com/ProjectQ-Framework/ProjectQ/files/8927520/pq_log.txt)
.

**Comment by CalMacCQ** [comment]
Okay I've ran 

``python3 -m pip install --no-cache-dir -v projectq > pq_log1.txt``

 in the same directory. Let me know if you need anything else. Just in case its relevant I ran the command in my previous comment in a new virtual environment so I'm not sure there would be an issue with a previous installation. 
 
 Let me know if you need anything else. Thanks again.
 
[pq_log1.txt](https://github.com/ProjectQ-Framework/ProjectQ/files/8929169/pq_log1.txt)
s

**Comment by Takishima** [comment]
> Okay I've ran
> 
> `python3 -m pip install --no-cache-dir -v projectq > pq_log1.txt`
> 
> in the same directory. Let me know if you need anything else. Just in case its relevant I ran the command in my previous comment in a new virtual environment so I'm not sure there would be an issue with a previous installation.
> 
> Let me know if you need anything else. Thanks again.
> 
> [pq_log1.txt](https://github.com/ProjectQ-Framework/ProjectQ/files/8929169/pq_log1.txt)

It does not matter if you ran the previous one in a virtual environment, that's perfectly fine. I suspect the issue comes from some compilation options that is passed to the C++ compiler.

My apologies but I am going to have to ask you to run the pip command once more because this time around ProjectQ was already installed and so basically nothing happened... 😅

```bash
python3 -m pip uninstall -y project
python3 -m pip install --no-cache-dir -v projectq > pq_log2.txt
```

**Comment by CalMacCQ** [comment]
Hi,

No worries :) I've ran the above commands and here is the txt file. Thanks
[pq_log2.txt](https://github.com/ProjectQ-Framework/ProjectQ/files/8949185/pq_log2.txt)
.

**Comment by Takishima** [comment]
Ehm... there was a typo in the first of the commands I asked you to run... a 'q' was missing so you did not actually uninstall ProjectQ with the first one and reinstall it right afterwards...

```bash
python3 -m pip uninstall -y projectq
python3 -m pip install --no-cache-dir -v projectq > pq_log2.txt
```

**Comment by CalMacCQ** [comment]
Yes I suspected there was a typo and added the 'q' to the first command (I should've said) I received a confirmation that projectq was successfully uninstalled.

**Comment by CalMacCQ** [comment]
Its possible I could've missed something else so I've reran both of these commands again (see screenshots) Looking in the pq_log3.txt file I also do not see the compiler tests or the other # INFO statements you have shared above so I'm not sure whats gone wrong here.

<img width="1057" alt="Screenshot 2022-06-21 at 21 42 44" src="https://user-images.githubusercontent.com/93673602/174894577-5c98e418-1f79-466a-8525-508cc243776d.png">
<img width="921" alt="Screenshot 2022-06-21 at 21 41 29" src="https://user-images.githubusercontent.com/93673602/174894604-81246973-38ac-4523-a450-98dc959e8824.png">
[pq_log3.txt](https://github.com/ProjectQ-Framework/ProjectQ/files/8952707/pq_log3.txt)
.

**Comment by CalMacCQ** [comment]
[pq_log3.txt](https://github.com/ProjectQ-Framework/ProjectQ/files/8952714/pq_log3.txt)

**Comment by Takishima** [comment]
Could you try to update `pip`, `setuptool` and `wheel` ?

```
python3 -m pip install -U pip setuptools wheel`
```

**Comment by CalMacCQ** [comment]
Hi again,

I have updated pip, setuptools and wheel. I have also set up a new virtual environment and ran

`python3 -m pip install --no-cache -v projectq --log log_file`

Using this command seems to do a better job of logging the installation. I think the command I was using before was the wrong way to do this so apologies. 

I can now see the compiler tests in the log and a warning about OpenMP.

I hope the log file is more helpful this time. 
Thank
[log_file.txt](https://github.com/ProjectQ-Framework/ProjectQ/files/8990450/log_file.txt)
s

**Comment by Takishima** [comment]
Thanks for the new log, this time I can see everything.

Unfortunately, I do not have an Apple M1 machine to test things on, but I am assuming that the issue comes from the fact that we are using AVX2 instructions in the C++ simulator.

The compiler test for it succeeds (since no error message):
```
...
2022-06-27T10:10:02,359   gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/opt/anaconda3/include -arch x86_64 -I/opt/anaconda3/include -arch x86_64 -I/Users/callum/Desktop/new_test/test_env/include -I/opt/anaconda3/include/python3.8 -c /var/folders/p1/hhrjrbd50hq35l9hgk8567tc0000gn/T/tmpxxr456s8.cpp -o var/folders/p1/hhrjrbd50hq35l9hgk8567tc0000gn/T/tmpxxr456s8.o -mavx2
...
```

but then the Apple compatibility layer is unable to properly translates the AVX2 instructions when running the code it seems. I will submit a PR to address those issues in the coming days.

**Comment by Takishima** [comment]
In the mean time, try updating your Python version to at least 3.9.1 since that was the first python version that officially supported the Apple M1 (according to https://isapplesiliconready.com/app/Python)

**Comment by Takishima** [comment]
Just mention that I have not forgotten about this issue and will try to come up with a fix soon.

**Comment by CalMacCQ** [comment]
Great :) apologies for the gap I got a bit bogged down upgrading my python version.

**Comment by CalMacCQ** [comment]
Just a note that in the above thread I was using my system python (version 3.8.8). I have now upgraded to python 3.10.6 using pyenv and I have no issues importing and using projectq.

I'm not sure what the issue was here but after upgrading it seems to have resolved itself.

**Comment by Takishima** [comment]
Ok, so it was indeed due to the fact that Python < 3.9 are not officially supported on ARM-powered macs.
