### ISSUE TITLE
Add support for initializing Simulator to a specific state

### ISSUE THREAD

**Issue by Strilanc** [ProjectQ-Framework/ProjectQ#42]
This would be useful for testing circuits. Particularly for circuits that happen to be classical, since then a single run of the simulator can be used to test every case by comparing amplitudes in the output vector to the amplitude it should have come from in the input vector.

**Comment by thomashaener** [comment]
So by state you mean individual amplitudes, rather than initializing to a classical bit-string?

**Comment by Strilanc** [comment]
Yes.

An alternative approach, for this use case, is a "PermutationSimulator" which only allows classical gates and then spits out the final permutation.

**Comment by thomashaener** [comment]
Ok the idea was actually to use the `cheat` function for this. Unfortunately, the default pybind export of std::vector performs a copy each time a switch between Python and C++ is made, which is why this currently does not work. At some point, we should implement a custom version of this and update the C++ export.

**Comment by thomashaener** [comment]
Oh and we'll definitely need a permutation simulator.

**Comment by hsim13372** [comment]
I'm currently working on testing out different initial states for the VQE so being able to initialize the ProjectQ Simulator to a specific state would be very useful!

**Comment by thomashaener** [comment]
I'll add an extra function over the weekend since I currently don't see a quick fix for the pybind issue with cheat.

**Comment by damiansteiger** [comment]
This feature has been added to the Simulator in the develop branch, see 
http://projectq.readthedocs.io/en/latest/projectq.backends.html#projectq.backends.Simulator.set_wavefunction

Thanks @thomashaener
