### ISSUE TITLE
BasicQubit hash is inconsistent

### ISSUE THREAD

**Issue by Strilanc** [ProjectQ-Framework/ProjectQ#43]
The most important condition that hash functions must satisfy is `a == b implies hash(a) == hash(b)`, but the BasicQubit class doesn't meet it:

    a = _qubit.BasicQubit(fake_engine, 5)
    b = _qubit.BasicQubit(fake_engine, 5)
    assert a == b
    assert hash(a) == hash(b)

The existing tests are checking for inequality instead of equality, i.e. that `a != b implies hash(a) != hash(b)`. Which is actually not a requirement of hash functions at all, though it matters for performance.

**Comment by thomashaener** [comment]
While the hash would remain inconsistent, we could add support for all cases where `id != -1` without any further changes.
Alternatively, we can substitute the `MainEngine`'s WeakSet with some other data structure...
