### ISSUE TITLE
Script runs on the simulator but encounters error on real IBM QE backend regarding a non-existent 'u2' gate

### ISSUE THREAD

**Issue by JohnSlick** [ProjectQ-Framework/ProjectQ#443]
Hello projectq team, you do amazing work.

The following teleport script runs on the simulator but encounters an error on the real IBM QE backend. **The IBM QE job runtime error states that this script is using a 'u2' gate, but it for sure is not.** If this script runs on the simulator, why does this error occur on the real IBM QE? What should I change to make it run on the real IBM QE, like the simulator?
> https://www.dropbox.com/s/vldt8mde6wn8atb/projectq_teleport.py?dl=0

To run this script, set the following variables:
> IBM_QE
> message
> device
> token

When viewing the job status on IBM QE via a browser, the 'Status Description' of the job states:

    The Qobj uses gates (['u2']) that are not among the basis gates (['id', 'rz', 'sx', 'x', 'cx', 'reset']) [1106]

    https://quantum-computing.ibm.com/admin/docs/admin/manage/errors#error1106

    Error 106: The Qobj uses gates that are not among the backend’s basis gates.

    Correct your program and try again.
    Transpiling your program will convert high level gates to basis gates.
    The basis gates for a backend can be found in its configuration data.

Here is the full local python console error:
> https://www.dropbox.com/s/ebqv4et411vm0zq/2022-08-14-projectq_teleport-ERROR_VALIDATING_JOB.txt?dl=0

Thank you for taking a look at this.

**Comment by Takishima** [comment]
Could you try to add a `CommandPrinter` engine in the engine list when running the code? This would print any gates to the console.

I would modify your script and add one line just after this one:
```python
    compiler_engines = projectq.setups.ibm.get_engine_list(token=token, device=device)
```
Line to add:
```python
    compiler_engines.append(CommandPrinter)
```

**Comment by Takishima** [comment]
The issue might arise because some other gates get decomposed down to `U2` when executing your code.

**Comment by JohnSlick** [comment]
Thank you @Takishima. After making those changes, the below UnsupportedEngineError is raised. Would you advise I use one of the setups that includes an AutoReplacer in the following link? I started testing some, but have not yet been successful.
https://projectq.readthedocs.io/en/latest/_doc_gen/projectq.setups.html

```
Traceback (most recent call last):
  File "/home/<REDACTED>/PycharmProjects/Retribution/projectq/projectq_teleport.py", line 120, in <module>
    quantum_engine = MainEngine(IBMBackend(token=token, use_hardware=True, num_runs=1024,
  File "/usr/local/lib/python3.10/dist-packages/projectq/cengines/_main.py", line 156, in __init__
    raise UnsupportedEngineError(
projectq.cengines._main.UnsupportedEngineError: 
You supplied an unsupported engine in engine_list,
i.e. not an instance of BasicEngine.
Did you forget the brackets to create an instance?
E.g. MainEngine(engine_list=[AutoReplacer]) instead of
     MainEngine(engine_list=[AutoReplacer()])
```

**Comment by Takishima** [comment]
Ah, my bad... my suggestion was missing the `()` after `CommandPrinter`:

```python
    compiler_engines.append(CommandPrinter())
```

**Comment by JohnSlick** [comment]
It's ok, thanks for clarifying. After adding the "()",  the Status Description for the Job still shows:

`The Qobj uses gates (['u2']) that are not among the basis gates (['id', 'rz', 'sx', 'x', 'cx', 'reset']) [1106] `

I'm going to start researching how to make the `AutoReplacer` coupled to an `InstructionFilter` work. I appreciate your guidance.

**Comment by Takishima** [comment]
But when you ran the code, did you not see any printouts of commands being executed ?

A code like this

```python
from projectq.backends import CommandPrinter
from projectq.cengines import MainEngine

eng= MainEngine(engine_list=[CommandPrinter()])
qubit = eng.allocate_qubit()
eng.flush()
```

would generate output like this on the console:

```
Allocate | Qureg[0]
Deallocate | Qureg[0]
```

**Comment by JohnSlick** [comment]
Yes, here is a link to the command printouts from the console:

> https://www.dropbox.com/s/96q1uu6molesv9n/2022-09-10-projectq_teleport-ERROR_VALIDATING_JOB.txt?dl=0

Also, the script link has been updated to include the `CommandPrinter()` logic:

> https://www.dropbox.com/s/vldt8mde6wn8atb/projectq_teleport.py?dl=0

**Comment by JohnSlick** [comment]
I realize now this is not really an issue, but the engine just needs to be built correctly. I will close out this issue. Thank you for your direction @Takishima, I sent you an email.
