### ISSUE TITLE
NoGateDecompositionError: No replacement found for Measure^\dagger | Qureg[16]!

### ISSUE THREAD

**Issue by saifawan2703** [ProjectQ-Framework/ProjectQ#475]
Hello,

I encountered a  **NoGateDecompositionError** while using the ProjectQ framework. The specific error message is:
 No replacement found for Measure^\dagger | Qureg[16]!
Could anyone provide insights on what might be causing this issue? Are there specific conditions under which this error occurs, and how can I resolve it?

**Comment by damiansteiger** [comment]
The error happens because there exists no inverse of a measurement ("Measure^\dagger").

Did you accidentally use `Measure` within a  `with Dagger(eng)` section?
