### ISSUE TITLE
How to Implement Multi-Controlled X Gate in ProjectQ Like Qiskit's qc.mcx([0, 1, 3], 2)?

### ISSUE THREAD

**Issue by saifawan2703** [ProjectQ-Framework/ProjectQ#478]
Hello ProjectQ Community,

I am transitioning from Qiskit to ProjectQ and I’m trying to replicate a specific operation. In Qiskit, I can use the following code to apply a multi-controlled X gate:
qc.mcx([0, 1, 3], 2)
I would like to know how to achieve the same functionality in ProjectQ. Is there a built-in function for multi-controlled X gates, or do I need to implement it manually? If manual implementation is required, could someone provide an example?

Thank you for your help!

**Comment by damiansteiger** [comment]
You can achieve this with a `ControlledGate` or `C()`, see
https://projectq.readthedocs.io/en/latest/_doc_gen/projectq.ops.html#projectq.ops.ControlledGate
