### ISSUE TITLE
Issue Running Code with 40 Qubits

### ISSUE THREAD

**Issue by saifawan2703** [ProjectQ-Framework/ProjectQ#479]
Hi everyone,

I have written a simple code snippet that utilizes 40 qubits, as shown below. However, I am encountering an error when trying to run it on a server with 128 GB of RAM.

Could this issue be related to memory space, or is there another underlying problem causing the code to fail?
```
def Simple_function(eng):
    k0 = eng.allocate_qureg(8)
    k1 = eng.allocate_qureg(8)
    x = eng.allocate_qureg(8)  # high
    y = eng.allocate_qureg(8)  # low
    z = eng.allocate_qureg(8)

eng = projectq.MainEngine(backend=Simulator(gate_fusion=True), engine_list=[])
Simple_function(eng)
```

**Comment by damiansteiger** [comment]
This is a memory issue. 40 qubits require 16TB of RAM (see [simulator tutorial](https://github.com/ProjectQ-Framework/ProjectQ/blob/develop/examples/simulator_tutorial.ipynb))

**Comment by saifawan2703** [comment]
thanks sir, and one more question. Which  Simulator is best  for Implementing Grover's Algorithm in ProjectQ?

**Comment by damiansteiger** [comment]
In regards to #480: `Simulator` vs `ClassicalSimulator` 
As Grover contains quantum operations, the `Simulator` is required. For only debugging a classical Grover oracle (without the quantum parts), the `ClassicalSimulator` is sufficient.
