### ISSUE TITLE
Suggestion: LimitedCapabilityEngine

### ISSUE THREAD

**Issue by Strilanc** [ProjectQ-Framework/ProjectQ#55]
For testing decompositions, it's often useful to prevent AutoReplacer from passing along complicated gates. This functionality could go into DummyEngine, but separating it out keeps DummyEngine simple.

See https://github.com/ProjectQ-Framework/ProjectQ/pull/54 for the basic idea.

**Comment by thomashaener** [comment]
Sure, why not. While it is basically an InstructionFilter, it's nice to have for testing.

**Comment by Strilanc** [comment]
Oh, you *do* have an existing engine for this. In that case it would make more sense to merge behaviors into it rather than make a separate one.

**Comment by thomashaener** [comment]
I think having a separate one makes sense, but the new one can, e.g., derive from `InstructionFilter`.
