### ISSUE TITLE
Give register sizes to BasicMathGate's function

### ISSUE THREAD

**Issue by Strilanc** [ProjectQ-Framework/ProjectQ#65]
Some classical operations need to know the size of the register they are applying to. For example: left-rotate, right-rotate, reverse, etc (anything that involves permuting bits).

There are also operations such as `3**(2**k) (mod 2^n)` that grow very large very fast if you don't know `n`.

**Comment by thomashaener** [comment]
Sure, we could have an `AdvancedBasicMathGate`, which does something similar to [this](http://projectq.ch/docs/projectq.ops.html#projectq.ops.BasicMathGate.__init__) (second example) by default.

**Comment by Strilanc** [comment]
I actually didn't realize this was the reason for the function that took the registers and returned the implementation. The existing thing does this.
