### ISSUE TITLE
[WIP] Fix Qubit.__del__ causing problems during abnormal shutdown

### ISSUE THREAD

**Issue by Strilanc** [ProjectQ-Framework/ProjectQ#93]
Based on to the answer to https://github.com/ProjectQ-Framework/ProjectQ/issues/85, the reason `MainEngine.__del__` exists and the reason `atexit` is used in MainEngine is to avoid issues caused by qubits being deallocated during sudden shutdowns (e.g. user hitting ctrl+C).

There are actually several places in the code doing acrobatics to work around the issue. And anytime a test fails, you tend to see a bunch of extra failures get tacked on due to the qubit deallocations running over code that failed halfway through in a bad state.

For example, here is a failing repro test:

```
def test_qubit_deallocate_reentrancy_safety():
    class InjectedBugEngine(_basics.BasicEngine):
        def __init__(self):
            _basics.BasicEngine.__init__(self)
            self.was_in_middle_of_receive = False
            self.x = []

        def receive(self, command_list):
            assert not self.was_in_middle_of_receive
            self.was_in_middle_of_receive = True

            for cmd in command_list:
                assert not isinstance(cmd.gate, DeallocateQubitGate)
                if not isinstance(cmd.gate, AllocateQubitGate):
                    self.x[1] = None  # Trigger IndexError

            self.was_in_middle_of_receive = False

    bug_eng = InjectedBugEngine()
    eng = MainEngine(backend=bug_eng, engine_list=[])

    try:
        q = eng.allocate_qubit()[0]
        try:
            H | q  # Triggers injected IndexError bug.
        finally:
            q.__del__()  # Force dealloc of q, as if it went out of scope.
    except IndexError:
        pass  # Expected.

    assert bug_eng.was_in_middle_of_receive
```

This test fails not once but *twice*. Both times on the `assert not self.was_in_middle_of_receive` line. One due to the manual call to `q.__del()__`, and another in `atexit` while the interpreter is shutting down.

To fix this problem, we need to make engines re-entrant safe against qubit deallocations. I suggest introducing a `defer_deallocate_qubit` method that puts the deallocate command into a queue. Then, before each non-reentrant call to receive, the engine drains that queue.

So, during shutdown, the command will go into a queue and just not do anything. But during actual use, the user will call Allocate or Flush or `H | something`, and the deallocate will appear in the same order as usual. The main change will be that circuits may be missing deallocates at the end, but those deallocates don't matter anyways.

More concretely, I'm going to make all of these fixes (most have to happen at the same time because they depend on each other):

0. Add an `already_deallocated` field to Qubit, and use it in `__del__` so that it can't re-enter itself anymore.
0. Move `DirtyQubitTag` to cengines (but still expose it from meta) so there's no in-method imports needed to create dirty deallocate commands.
0. Add the above test to _basis_tests
0. Add a `drain_deferreds_and_receive` to BasicEngine that drains deferred commands before calling `receive`.
0. Change all existing `receive` calls to either `send` or `drain_deferreds_and_receive`.

The reason I'm adding a new method, instead of replacing `receive`, is that this method is not intended to be overridden. It's a breaking change that should be considered separately.

**Comment by thomashaener** [comment]
Actually, most of this was done to have the same behavior, whether qubits are allocated within a function or not. If one allocates a huge number of qubits and then does nothing to them, the optimizer should be able to remove these qubits. Thus I think `Deallocate` gates are important.

The issue with qubits being deallocated multiple times can be fixed easily: The qubit should set its own id to -1, then send a BasicQubit with the original ID to engine.deallocate_qubit.

**Comment by Strilanc** [comment]
Setting the id to -1 only happens after the call to Deallocate. When a broken engine throws an exception during the deallocate call, an infinite loop where the __del__ method keeps running and failing again and again can happen.

**Comment by thomashaener** [comment]
But that's exactly what I'm saying: Changing the order in which this happens fixes the issue.

**Comment by thomashaener** [comment]
In __del__:
```
my_id = self.id
self.id = -1
self.engine.deallocate_qubit(BasicQubit(self.engine, my_id)
```

**Comment by Strilanc** [comment]
Ah, that also works. I'll update https://github.com/ProjectQ-Framework/ProjectQ/pull/95

**Comment by thomashaener** [comment]
Cool, thanks!

**Comment by Strilanc** [comment]
Ah, there's an issue. One of the tests fails; it seems to expect the id to be preserved on failure:

```
def test_simulator_no_uncompute_exception(sim):
    eng = MainEngine(sim, [])
    qubit = eng.allocate_qubit()
    H | qubit
    with pytest.raises(RuntimeError):
        qubit[0].__del__()
    Measure | qubit
```

**Comment by Strilanc** [comment]
I'm just going to cut the test. When del fails, bad things are afoot and you shouldn't be continuing to use that qubit.

**Comment by thomashaener** [comment]
I agree, except that in this case we're testing for a feature of the simulator. I'd recommend removing the measurement.

**Comment by Strilanc** [comment]
Ah, right of course. I meant cut the specific implicit assertion that measurement worked afterward.

**Comment by Strilanc** [comment]
Here's something gross that might work:

```
import atexit
_is_exiting = False
def _mark_exiting():
    global _is_exiting
    _is_exiting = True
atexit.register(_mark_exiting)


class Qubit():
    def __del__(self):
        if _is_exiting:
            return
        print("do __del__")
```
