### ISSUE TITLE
Suggestion: make `develop` the default branch for the github repo

### ISSUE THREAD

**Issue by Strilanc** [ProjectQ-Framework/ProjectQ#99]
Because most activity happens on develop, it's usually the one I want to be looking at / merging into / etc. For looking at specific releases I'd go to the release tab and see the tags.

**Comment by thomashaener** [comment]
Yes, but I think having the release branch as default makes it easier for less experienced users.

**Comment by maffoo** [comment]
I suspect that most inexperienced users are just going to pip install projectq. If someone wants to check out the repo from github to run from source, they already need to know something about git, etc. In that case it's not too hard to checkout a particular tag if you want a specific version, but I would think the more common thing is you want to have the latest pre-release code.

**Comment by Strilanc** [comment]
I agree with Matthew. People expect a github repo to be centered around development of the code.

For example, sampling from ProjectQ's own dependencies:

- `numpy` defaults to a development branch (master) [instead of one of their maintenance branches]
- `future` doesn't seem to have a github reo
- `pytest` defaults to a development branch (master) [they don't have stable branches, just release tags]
- `pybind11`defaults to a development branch (master) [instead of their stable branch]
- `requests` defaults to a development branch (master) [they don't have stable branches, just release tags]
- `scipy` defaults to a development branch (master) [instead of one of their maintenance branches]

Suffice it to say it's a pretty common convention to not only have the default branch be the development branch, but also for the development branch to be called 'master'. [Google also develops code this way, with everything constantly merging into a master trunk.](https://cacm.acm.org/magazines/2016/7/204032-why-google-stores-billions-of-lines-of-code-in-a-single-repository/fulltext)

**Comment by babbush** [comment]
I do not care much what happens with ProjectQ but I feel very strongly that FermiLib should default to the develop branch.

**Comment by thomashaener** [comment]
We can just add a statement to the 'getting started' section for people who don't know github but can't use pip (might be blocked by the employer).
